[package]
name = "dices-server-migration"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
async-std = { version = "1", features = ["attributes", "tokio1"] }

[dependencies.sea-orm-migration]
version = "1.0.0"
features = ["runtime-tokio-rustls", "sqlx-postgres"]
