[package]
name = "dices-tui"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "dices"
path = "src/main.rs"

[dependencies]
dices-engine.workspace = true
dices-man.workspace = true
dices-parser.workspace = true
dices-print.workspace = true
dices-std.workspace = true
dices-values.workspace = true

chrono = "0.4.45"
clap = { version = "4.6.1", features = ["derive", "env", "string", "wrap_help"] }
const_format = { version = "0.2.36", features = ["fmt"] }
crossterm = { version = "0.29.0", features = ["serde"] }
directories = "6.0.0"
figment = { workspace = true, features = ["env", "toml"] }
itertools.workspace = true
nu-ansi-term = { version = "0.50.3", features = ["derive_serde_style", "serde"] }
pretty = { workspace = true, features = ["termcolor"] }
rand.workspace = true
rand_seeder.workspace = true
reedline = "0.48.0"
rust-embed.workspace = true
serde.workspace = true
snafu.workspace = true
toml = "1.1.2"
yoke.workspace = true
elsa = "1.11.2"

[lints]
workspace = true
