[package]
name = "dices-man"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
elsa = "1.11.2"
itertools.workspace = true
lazy-regex = "3.6.0"
linkme.workspace = true
rust-embed = { workspace = true, features = ["interpolate-folder-path"] }
snafu.workspace = true


[lints]
workspace = true
