[package]
name = "dices-values"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
derive_more = { workspace = true, features = ["full"] }
num = { version = "0.4.3", features = ["num-bigint", "rand", "serde"] }
snafu.workspace = true
yoke = "0.8.3"

[lints]
workspace = true
