[workspace]
members = ["ast", "engine", "man", "mantest", "repl", "version", "ast/macros"]
default-members = ["repl"]
resolver = "2"

[workspace.package]
version = "0.3.1"
edition = "2021"
authors = ["zannabianca1997 <zannabianca199712@gmail.com>"]
license = "MIT"
