[package]
name = "dices"
default-run = "dices"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[workspace.package]
version = "3.1.0"
edition = "2021"
authors = ["zannabianca1997 <zannabianca199712@gmail.com>"]
license = "MIT"

[[bin]]
name = "dices"
path = "repl/src/main.rs"
required-features = ["repl"]

[[bin]]
name = "dices-server"
path = "server/src/main.rs"
required-features = ["server"]

[[bin]]
name = "dices-server-migration"
path = "server/migration/src/main.rs"
required-features = ["server"]

[features]
default = ["repl"]
server = ["dep:dices-server", "dep:dices-server-migration"]
repl = ["dep:dices-repl"]

[dependencies]
dices-repl = { path = "repl", optional = true }
dices-server = { path = "server", optional = true }
dices-server-migration = { path = "server/migration", optional = true }

[workspace]
members = [
    "ast",
    "engine",
    "man",
    "mantest",
    "repl",
    "server",
    "server/migration",
    "version",
]
resolver = "2"
