[workspace]
members = [
    "ast",
    "engine",
    "man",
    "mantest",
    "repl",
    "server",
    "server/migration",
    "version",
]
default-members = ["repl"]
resolver = "2"

[workspace.package]
version = "3.1.0"
edition = "2021"
authors = ["zannabianca1997 <zannabianca199712@gmail.com>"]
license = "MIT"
