[workspace]
resolver = "3"
members = ["ast", "engine", "parser", "tui", "values"]

[workspace.package]
version = "0.4.0"
edition = "2024"
license = "MIT"

[workspace.dependencies]
dices-ast = { path = "ast" }
dices-engine = { path = "engine" }
dices-parser = { path = "parser" }
dices-values = { path = "values" }

derive_more = { version = "2.1.1", features = ["full"] }
itertools = "0.15.0"
num = { version = "0.4.3", features = ["num-bigint", "rand", "serde"] }
rand = "0.8.6"
serde = { version = "1.0.228", features = ["derive"] }
snafu = "0.9.1"

strum = { version = "0.28.0", features = ["derive"] }

[workspace.lints.rust]
unsafe_op_in_unsafe_fn = "deny"
