[workspace]
resolver = "3"
members = [
  "ast",
  "engine",
  "man",
  "parser",
  "print",
  "std",
  "tui",
  "values",
  "values/macros"
]

[workspace.package]
version = "0.4.0"
edition = "2024"
license = "MIT"

[workspace.dependencies]
dices-ast = { path = "ast" }
dices-engine = { path = "engine" }
dices-man = { path = "man" }
dices-parser = { path = "parser" }
dices-print = { path = "print" }
dices-std = { path = "std" }
dices-values = { path = "values" }
dices-values-macros = { path = "values/macros" }

derive_more = { version = "2.1.1", features = ["full"] }
figment = { version = "0.10.19", features = ["env", "toml"] }
itertools = "0.15.0"
num = { version = "0.4.3", features = ["num-bigint", "rand", "serde"] }
pretty = { version = "0.12.5", features = ["termcolor"] }
rand = "0.8.6"
rand_seeder = "0.3.0"
rust-embed = { version = "8.11.0", features = ["interpolate-folder-path"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0"
snafu = "0.9.1"
strum = { version = "0.28.0", features = ["derive"] }

[workspace.lints.clippy]
result_large_err = "allow"

[workspace.lints.rust]
unsafe_op_in_unsafe_fn = "deny"
