[package]
name = "dices"
version = "0.1.0"
edition = "2021"
authors = ["zannabianca1997 <zannabianca199712@gmail.com>"]
description = "A program to simulate dice throwing"

[dependencies]
lazy_static = "1.4.0"
pest = "2.5.6"
pest_derive = "2.5.6"
rand = { version = "0.8.5", features = ["small_rng"] }
rustyline = "11.0.0"
thiserror = "1.0.40"
strum_macros = "0.24"
strum = { version = "0.24", features = ["derive"] }
phf = { version = "0.11", features = ["macros"] }
lazy-regex = "2.5.0"
pad = "0.1.6"
either = "1.8.1"
