WHITESPACE = _{ " " | "\t" | "\n" | "\r" }
COMMENT    = _{ "/*" ~ (!"*/" ~ ANY)* ~ "*/" | "//" ~ (!"\n" ~ ANY)* }

main = { SOI ~ scope_inner ~ EOI }

scope_inner   = { statement_semi* ~ expr? }
statement_semi = { statement ~ ";" }
scope         = { "{" ~ scope_inner ~ "}" }

statement = { expr | "" }

expr = { join }

join        = { or ~ ("~" ~ or)* }
or          = { and ~ ("||" ~ and)* }
and         = { cmp ~ ("&&" ~ cmp)* }
cmp         = { add ~ (cmp_op ~ add)* }
add         = { mul ~ (add_op ~ mul)* }
mul         = { unary ~ (mul_op ~ unary)* }
unary       = { unary_op ~ unary | repeat }
repeat      = { dice_unary ~ ("^" ~ dice_unary)* }
dice_unary  = { dice_keyword ~ dice_unary | dice_binary }
dice_binary = { atom ~ ("d" ~ atom)* }

atom = { literal | "(" ~ expr ~ ")" | scope | list | map }

list = { "[" ~ (expr ~ ("," ~ expr)* ~ ","?)? ~ "]" }
map  = { "<|" ~ ((string ~ ":" ~ expr) ~ ("," ~ string ~ ":" ~ expr)* ~ ","?)? ~ "|>" }

literal =  { int | string | bool | null }
int     = @{ ASCII_DIGIT+ }
string  = @{ "\"" ~ (("\\" ~ ANY) | (!"\"" ~ ANY))* ~ "\"" }
bool    = @{ "true" | "false" }
null    = @{ "null" }

cmp_op       = { "<=" | ">=" | "==" | "!=" | "<" | ">" }
add_op       = { "+" | "-" }
mul_op       = { "*" | "/" | "%" }
unary_op     = { "+" | "-" | "!" }
dice_keyword = { "d" }
