WHITESPACE = _{ " " | "\t" | "\n" | "\r" }
COMMENT    = _{ "/*" ~ (!"*/" ~ ANY)* ~ "*/" | "//" ~ (!"\n" ~ ANY)* }

main = { SOI ~ scope_inner ~ EOI }

scope_inner   = { statement_semi* ~ statement? }
statement_semi = { statement ~ ";" }
statement      = { assign | expr | "" }
assign         = { let_stmt | set_stmt }
scope         = { "{" ~ scope_inner ~ "}" }
let_stmt   = { "let" ~ identifier ~ equals ~ expr }
set_stmt   = { identifier ~ equals ~ expr }
equals     = { "=" }
identifier = @{ (ASCII_ALPHA | "_") ~ (ASCII_ALPHANUMERIC | "_")* }

expr = { join }

join        = { or ~ ("~" ~ or)* }
or          = { and ~ ("||" ~ and)* }
and         = { cmp ~ ("&&" ~ cmp)* }
cmp         = { add ~ (cmp_op ~ add)* }
add         = { mul ~ (add_op ~ mul)* }
mul         = { unary ~ (mul_op ~ unary)* }
unary       = { unary_op ~ unary | filter }
filter      = { filter_atom ~ (filter_op ~ filter_atom)* }
filter_atom = { repeat | variable }
variable    = { identifier }
repeat      = { dice_unary ~ ("^" ~ dice_unary)* }
dice_unary  = { dice_keyword ~ dice_unary | dice_binary }
dice_binary = { dice_atom ~ ("d" ~ dice_atom)* }
dice_atom   = { atom | variable }

atom = { literal | "(" ~ expr ~ ")" | scope | list | map }

list = { "[" ~ (expr ~ ("," ~ expr)* ~ ","?)? ~ "]" }
map  = { "<|" ~ ((string ~ ":" ~ expr) ~ ("," ~ string ~ ":" ~ expr)* ~ ","?)? ~ "|>" }

literal =  { int | string | bool | null }
int     = @{ ASCII_DIGIT+ }
string  = @{ "\"" ~ (("\\" ~ ANY) | (!"\"" ~ ANY))* ~ "\"" }
bool    = @{ "true" | "false" }
null    = @{ "null" }

cmp_op       = { "<=" | ">=" | "==" | "!=" | "<" | ">" }
add_op       = { "+" | "-" }
mul_op       = { "*" | "/" | "%" }
unary_op     = { "+" | "-" | "!" }
dice_keyword = @{ "d" ~ !(ASCII_ALPHA | "_") }
filter_op    = { "kh" | "kl" | "rh" | "rl" }
