WHITESPACE = _{ " " | "\t" | "\n" | "\r" }

main = { SOI ~ value ~ EOI }

value = {
    null | bool | int | string | list | map
}

int    = @{ "-"? ~ ASCII_DIGIT+ }
string = @{ "\"" ~ (("\\" ~ ANY) | (!"\"" ~ ANY))* ~ "\"" }
bool   = @{ "true" | "false" }
null   = @{ "null" }

list    =  { "[" ~ (value ~ ("," ~ value)* ~ ","?)? ~ "]" }
map     =  { "<|" ~ ((map_key ~ ":" ~ value) ~ ("," ~ map_key ~ ":" ~ value)* ~ ","?)? ~ "|>" }
map_key = _{ string | identifier }

identifier     = @{ (ASCII_ALPHA | "_") ~ (ASCII_ALPHANUMERIC | "_")* }
