[package]
name = "dices-print"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
dices-man.workspace = true
dices-values.workspace = true

itertools.workspace = true
nunny = "0.2.2"
optional_struct = "0.5"
pretty.workspace = true
pulldown-cmark = "0.13.4"
simplecss = "0.2"
snafu.workspace = true
yoke = { workspace = true, features = ["derive"] }

[lints]
workspace = true
