[package]
name = "engine"
version = "0.1.0"
edition = "2021"

[dependencies]
either = "1.12.0"
lazy-regex = "3.1.0"
rand = { version = "0.8.5", features = ["small_rng"] }
strum = { version = "0.26.2", features = ["derive"] }
