[package]
name = "dices-engine"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
dices-ast.workspace = true
dices-values.workspace = true

itertools.workspace = true
num.workspace = true
rand.workspace = true
rand_pcg = { version = "0.3.1", features = ["serde"] }
snafu.workspace = true

[lints]
workspace = true
