[package]
name = "dices-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "dices"
path = "src/main.rs"

[dependencies]
dices-engine.workspace = true
dices-man.workspace = true
dices-parser.workspace = true
dices-print.workspace = true
dices-print-cli.workspace = true
dices-print-html = { workspace = true, optional = true }
dices-std.workspace = true
dices-values.workspace = true

chrono = "0.4.45"
clap = { version = "4.6.1", features = ["derive", "env", "string", "wrap_help"] }
crossterm = { version = "0.29.0", features = ["serde"] }
derive_more.workspace = true
directories = "6.0.0"
elsa = "1.11.2"
figment = { workspace = true, features = ["env", "toml"] }
itertools.workspace = true
lazy-regex = "3.6.0"
nu-ansi-term = { version = "0.50.3", features = ["derive_serde_style", "serde"] }
pretty.workspace = true
rand.workspace = true
rand_seeder.workspace = true
reedline = "0.48.0"
rust-embed.workspace = true
serde.workspace = true
snafu.workspace = true
termcolor = "1.4.1"
tokio-util = { version = "0.7.18", default-features = false, optional = true }
toml = "1.1.2"
url.workspace = true
webbrowser = { version = "1.2.1", optional = true }
yoke.workspace = true

[dependencies.axum]
version = "0.8.9"
default-features = false
features = ["http1", "macros", "original-uri", "tokio"]
optional = true

[dependencies.tokio]
version = "1.52.3"
default-features = false
features = ["net", "rt"]
optional = true

[build-dependencies]
cargo-build.workspace = true

[features]
default = ["man-server"]
man-server = [
  "dep:axum",
  "dep:dices-print-html",
  "dep:tokio",
  "dep:tokio-util",
  "dep:webbrowser"
]

[lints]
workspace = true
