name: dices-server
services:
  dices-server-postgres:
    image: postgres:17.0-alpine3.20
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - ${POSTGRES_PORT}:5432
