[package]
name = "dices-ast"
version = "0.1.0"
edition = "2021"

[features]
matcher = []

[dependencies]
derive_more = { version = "1.0.0", features = ["full"] }
either = "1.13.0"
itertools = "0.13.0"
lazy-regex = "3.2.0"
peg = "0.8.4"
phf = { version = "0.11.2", features = ["macros"] }
strum = { version = "0.26.3", features = ["derive"] }
nunny = "0.2.1"

[dev-dependencies]
arbitrary = { version = "1.3.2", features = ["derive"] }
