[package]
name = "dices-server"
description = "A server to run instances of `dices`"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
dices-engine = { path = "../engine" }
dices-server-migration = { path = "./migration" }
dices-server-entities = { path = "./entities" }
dices-server-dtos = { path = "./dtos" }
