[package]
name = "dices-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
derive_more = { version = "1.0.0", features = ["full"] }
dices-ast = { path = "../dices-ast" }
nunny = "0.2.1"
rand = "0.8.5"
