# Catppuccin Latte
# https://github.com/catppuccin/palette

reset = true
bold = false
intense = false
underline = false
dimmed = false
italic = false
strikethrough = false
fg_color = "#4c4f69"

# Graphical fluff (emojis): subdued.
[fluff]
fg_color = "#8c8fa1"  # overlay1

[value.null]
fg_color = "#8c8fa1"  # overlay1
italic = true

[value.integer]
fg_color = "#fe640b"  # peach

[value.bool]
fg_color = "#8839ef"  # mauve

[value.string]
fg_color = "#40a02b"  # green

[value.string.escape]
fg_color = "#fe640b"  # peach

[value.delimiter]
depth = [
  { fg_color = "#df8e1d" },  # yellow
  { fg_color = "#1e66f5" },  # blue
  { fg_color = "#8839ef" },  # mauve
  { fg_color = "#179299" },  # teal
  { fg_color = "#04a5e5" },  # sky
  { fg_color = "#7287fd" },  # lavender
]

[value.punctuator]
fg_color = "#6c6f85"  # subtext0

[value.injected]
fg_color = "#df8e1d"  # yellow

[prompt]
fg_color = "#1e66f5"  # blue

[prompt.indicator]
fg_color = "#40a02b"  # green

[prompt.multiline]
fg_color = "#8c8fa1"  # overlay1

[prompt.right]
fg_color = "#8c8fa1"  # overlay1
