[package]
name = "dices-ast"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
dices-values.workspace = true

derive_more.workspace = true
lazy-regex = "3.6.0"
phf = { version = "0.14.0", features = ["macros"] }
pretty.workspace = true

[lints]
workspace = true
