[package]
name = "dices-parser"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
dices-ast.workspace = true
dices-values.workspace = true

derive_more.workspace = true
pest = { version = "2.8.6", features = ["miette-error"] }
pest_derive = "2.8.6"
snafu.workspace = true
miette = "7.6.0"

[lints]
workspace = true
