[package]
name = "dices-print-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
dices-engine.workspace = true
dices-man.workspace = true
dices-parser.workspace = true
dices-print.workspace = true
dices-std.workspace = true
dices-values.workspace = true

pretty.workspace = true
pulldown-cmark.workspace = true
termcolor = "1.4.1"
url.workspace = true

[lints]
workspace = true
