//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.2

use sea_orm::{entity::prelude::*, TryFromU64};
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize)]
#[sea_orm(schema_name = "public", table_name = "session")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: SessionId,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, DeriveValueType, Serialize, Deserialize)]
pub struct SessionId(Uuid);

impl TryFromU64 for SessionId {
    fn try_from_u64(n: u64) -> Result<Self, DbErr> {
        Uuid::try_from_u64(n).map(Self)
    }
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_one = "super::engine::Entity")]
    Engine,
    #[sea_orm(has_many = "super::session_user::Entity")]
    SessionUser,
}

impl Related<super::engine::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Engine.def()
    }
}

impl Related<super::session_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SessionUser.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        super::session_user::Relation::User.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::session_user::Relation::Session.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
